/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * UncountedTerminatedPods holds UIDs of Pods that have terminated but haven\'t been accounted in Job status counters.
 */
export class V1UncountedTerminatedPods {
  /**
   * Failed holds UIDs of failed Pods.
   */
  'failed'?: string[];
  /**
   * Succeeded holds UIDs of succeeded Pods.
   */
  'succeeded'?: string[];

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'failed',
      baseName: 'failed',
      type: 'Array<string>',
    },
    {
      name: 'succeeded',
      baseName: 'succeeded',
      type: 'Array<string>',
    },
  ];

  static getAttributeTypeMap() {
    return V1UncountedTerminatedPods.attributeTypeMap;
  }
}
